### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by myui** [qubole/Hive-JDBC-Storage-Handler#2]
I heard/found that this repository is copy of my repository and based on it.
https://github.com/myui/HiveJdbcStorageHandler

Most of class/method structures are same as mine. Also, comments are same as mime. This must not be coincidence. 

Please updates your license header to include the original author, following OSS software rule.

Since I was not adding license header to my repos, I updated the license header.

**Comment by snarayananqubole** [comment]
@myui  - apologies for the oversight. Will take in your PR and also put in the right links back to the original repo and add your name in contributor list in the README file.

FYI - we have credited the original repo in the blogpost: http://www.qubole.com/blog/product/hive-jdbc-storage-handler/

**Comment by snarayananqubole** [comment]
Merge PR from @myui

**Comment by myui** [comment]
Thank you for the prompt reply.

I'm happy seeing my old code is being used and getting improved.
